### ISSUE TITLE
Why not using Sigar library of Hyperic?

### ISSUE THREAD

**Issue by bobwenx** [cb372/metrics-sigar#3]
the sigar that this project using is 1.6.4 and package by fusesource.
why not using sigar from hyperic project?
just add the repository to POM:

```
 <repositories>
        <repository>
            <id>hyperic-external</id>
            <name>Hyperic External Dependencies Repository</name>
            <url>http://maven.hyperic.org/external</url>
            <releases>
                <enabled>true</enabled>
                <checksumPolicy>fail</checksumPolicy>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
 </repositories>
```

and the dependencies:

```
        <dependency>
            <groupId>org.hyperic</groupId>
            <artifactId>sigar</artifactId>
            <version>1.6.6.11</version>
        </dependency>

        <dependency>
            <groupId>org.hyperic</groupId>
            <artifactId>sigar</artifactId>
            <version>1.6.6.11</version>
            <type>zip</type>
            <classifier>libs</classifier>
        </dependency>

        <dependency>
            <groupId>org.hyperic</groupId>
            <artifactId>sigar</artifactId>
            <version>1.6.6.11</version>
            <type>zip</type>
            <classifier>libs-a</classifier>
        </dependency>
```

**Comment by cb372** [comment]
Thanks, I didn't know Hyperic had their own repo. I'll give it a try.

**Comment by bobwenx** [comment]
i found it in [Hyperic HQ](https://github.com/hyperic/hq) project. and in [Hyperic External](http://maven.hyperic.org/) repository, there are even new release for sigar(1.7).

**Comment by cb372** [comment]
Unfortunately it looks like from 1.6 onwards Hyperic no longer provide native libs for OSX. This is a show-stopper for me, as it means I can't run the tests on my dev machine.

**Comment by bobwenx** [comment]
ok, 1.6.x verions is fine, and this is the version that hyperic using. 
the Latest release(1.6.11) fix quite a lot bugs, perhaps this can resolve the problem of getting incorrect value.
